use bevy::prelude::*;
use serde::{Deserialize, Serialize};

mod component_stats;

use crate::spell_data::ResourceType;

pub use self::component_stats::*;
pub use crate::aura::*;
pub use crate::casting::*;
pub use crate::class_spec::*;
pub use crate::threat::*;

#[derive(
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Default,
)]
pub struct CharacterAppearance {
    pub sex: u8,
    pub skin_color: u8,
    pub face: u8,
    pub eye_color: u8,
    pub hair_style: u8,
    pub hair_color: u8,
    pub facial_style: u8,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
)]
pub struct Position {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
)]
pub struct Rotation {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
)]
pub struct Health {
    pub current: f32,
    pub max: f32,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
)]
pub struct Mana {
    pub current: f32,
    pub max: f32,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Default,
)]
pub struct Gold(pub u32);

/// A single resource pool (current/max) for a specific resource type.
///
/// Each class has a primary resource (Rage for Warriors, Energy for Rogues,
/// Mana for casters) plus potential secondary resources (Combo Points, Holy Power).
/// Resource behavior varies by type:
/// - **Mana**: starts full, drains on cast, regenerates passively
/// - **Rage**: starts empty, generated by damage dealt/taken, decays out of combat
/// - **Energy**: starts full, regenerates at 10/sec, capped at 100
/// - **Focus**: like energy but for Hunters (regenerates at 5/sec)
/// - **Combo Points**: 0–5, built by abilities, consumed by finishers
/// - **Holy Power**: 0–5, built by abilities, consumed by spenders
/// - **Runic Power**: like rage, generated by rune abilities, decays out of combat
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct ResourcePool {
    pub resource_type: ResourceType,
    pub current: f32,
    pub max: f32,
    /// Passive regeneration per second (0.0 for rage/combo points).
    pub regen_per_sec: f32,
    /// Whether the resource decays out of combat (rage, runic power).
    pub decays_out_of_combat: bool,
}

impl ResourcePool {
    /// Create a default pool for a resource type with standard WoW defaults.
    ///
    /// | Type | Max | Start | Regen | Decays |
    /// |------|-----|-------|-------|--------|
    /// | Mana | 0 (stat-based) | 0 | 0 (formula) | no |
    /// | Rage/Runic | 100 | 0 | 0 | yes (2/sec) |
    /// | Energy | 100 | 100 | 10/sec | no |
    /// | Focus | 100 | 100 | 5/sec | no |
    /// | Combo/Holy | 5 | 0 | 0 | no |
    pub fn for_type(resource_type: ResourceType) -> Self {
        let (current, max, regen, decays) = match resource_type {
            ResourceType::Mana => (0.0, 0.0, 0.0, false),
            ResourceType::Rage | ResourceType::RunicPower => (0.0, 100.0, 0.0, true),
            ResourceType::Energy => (100.0, 100.0, 10.0, false),
            ResourceType::Focus => (100.0, 100.0, 5.0, false),
            ResourceType::ComboPoints | ResourceType::HolyPower => (0.0, 5.0, 0.0, false),
        };
        Self {
            resource_type,
            current,
            max,
            regen_per_sec: regen,
            decays_out_of_combat: decays,
        }
    }

    /// Spend a resource. Returns `true` if the entity had enough.
    pub fn spend(&mut self, amount: f32) -> bool {
        if self.current < amount {
            return false;
        }
        self.current -= amount;
        true
    }

    /// Generate (add) a resource, clamped to max.
    pub fn generate(&mut self, amount: f32) {
        self.current = (self.current + amount).min(self.max);
    }

    /// Tick passive regeneration by `dt` seconds.
    pub fn tick_regen(&mut self, dt: f32) {
        if self.regen_per_sec > 0.0 {
            self.generate(self.regen_per_sec * dt);
        }
    }

    /// Tick decay (out of combat). Rage/Runic Power lose 2/sec.
    pub fn tick_decay(&mut self, dt: f32) {
        if self.decays_out_of_combat {
            self.current = (self.current - RESOURCE_DECAY_RATE * dt).max(0.0);
        }
    }
}

/// Rate at which rage/runic power decay out of combat (per second).
const RESOURCE_DECAY_RATE: f32 = 2.0;

/// Collection of resource pools on an entity.
///
/// Most entities have 1–2 resources (e.g. Mana + Combo Points for a Rogue
/// who multiclasses, or just Rage for a Warrior).
#[derive(Component, Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Resources {
    pub pools: Vec<ResourcePool>,
}

impl Resources {
    /// Get a resource pool by type.
    pub fn get(&self, resource_type: ResourceType) -> Option<&ResourcePool> {
        self.pools.iter().find(|p| p.resource_type == resource_type)
    }

    /// Get a mutable resource pool by type.
    pub fn get_mut(&mut self, resource_type: ResourceType) -> Option<&mut ResourcePool> {
        self.pools
            .iter_mut()
            .find(|p| p.resource_type == resource_type)
    }

    /// Whether the entity has enough of a resource to spend.
    pub fn can_afford(&self, resource_type: ResourceType, amount: f32) -> bool {
        self.get(resource_type).is_some_and(|p| p.current >= amount)
    }

    /// Create a standard resource pool for a class's primary resource.
    pub fn with_primary(resource_type: ResourceType) -> Self {
        Self {
            pools: vec![ResourcePool::for_type(resource_type)],
        }
    }
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
)]
pub struct MovementSpeed(pub f32);

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Default,
)]
pub struct CombatStatus(pub bool);

/// Vertical velocity in yards/sec (positive = upward).
#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
    Default,
)]
pub struct VerticalVelocity(pub f32);

/// Player is currently mounted. Removed on dismount.
#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    PartialEq,
)]
pub struct Mounted {
    /// Display ID of the mount.
    pub mount_display_id: u32,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    PartialEq,
)]
pub struct Player {
    pub name: String,
    pub race: u8,
    pub class: u8,
    pub appearance: CharacterAppearance,
}

#[derive(
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
)]
pub enum EquipmentVisualSlot {
    Head,
    Shoulder,
    Back,
    Chest,
    Shirt,
    Tabard,
    Wrist,
    Hands,
    Waist,
    Legs,
    Feet,
    MainHand,
    OffHand,
}

#[derive(
    Reflect, Serialize, Deserialize, bitcode::Encode, bitcode::Decode, Debug, Clone, PartialEq, Eq,
)]
pub struct EquippedAppearanceEntry {
    pub slot: EquipmentVisualSlot,
    pub item_id: Option<u32>,
    pub display_info_id: Option<u32>,
    pub inventory_type: u8,
    pub hidden: bool,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    PartialEq,
    Eq,
    Default,
)]
pub struct EquipmentAppearance {
    pub entries: Vec<EquippedAppearanceEntry>,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
)]
pub struct Npc {
    pub template_id: u32,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
)]
pub struct Zone {
    pub id: u32,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
)]
pub struct ModelDisplay {
    pub display_id: u32,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    PartialEq,
)]
pub struct GuildMembership {
    pub guild_id: u32,
    pub guild_name: String,
}

#[derive(
    Component,
    Reflect,
    Serialize,
    Deserialize,
    bitcode::Encode,
    bitcode::Decode,
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Default,
)]
pub enum PresenceStatus {
    #[default]
    Online,
    Afk,
    Dnd,
    Offline,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resource_pool_spend_sufficient() {
        let mut pool = ResourcePool::for_type(ResourceType::Energy);
        assert!(pool.spend(40.0));
        assert_eq!(pool.current, 60.0);
    }

    #[test]
    fn resource_pool_spend_insufficient() {
        let mut pool = ResourcePool::for_type(ResourceType::Rage);
        pool.generate(20.0);
        assert!(!pool.spend(30.0));
        assert_eq!(pool.current, 20.0, "should not deduct on failure");
    }

    #[test]
    fn resource_pool_generate_caps_at_max() {
        let mut pool = ResourcePool::for_type(ResourceType::Energy);
        pool.generate(50.0);
        assert_eq!(pool.current, 100.0);
    }

    #[test]
    fn resource_pool_regen_ticks() {
        let mut pool = ResourcePool::for_type(ResourceType::Energy);
        pool.current = 50.0;
        pool.tick_regen(2.0);
        assert_eq!(pool.current, 70.0);
    }

    #[test]
    fn resource_pool_decay_rage() {
        let mut pool = ResourcePool::for_type(ResourceType::Rage);
        pool.current = 50.0;
        pool.tick_decay(5.0);
        assert_eq!(pool.current, 40.0);
    }

    #[test]
    fn resource_pool_decay_clamps_to_zero() {
        let mut pool = ResourcePool::for_type(ResourceType::Rage);
        pool.current = 3.0;
        pool.tick_decay(5.0);
        assert_eq!(pool.current, 0.0);
    }

    #[test]
    fn resource_pool_energy_no_decay() {
        let mut pool = ResourcePool::for_type(ResourceType::Energy);
        pool.current = 50.0;
        pool.tick_decay(5.0);
        assert_eq!(pool.current, 50.0, "energy should not decay");
    }

    #[test]
    fn resources_with_primary_rage() {
        let res = Resources::with_primary(ResourceType::Rage);
        let pool = res.get(ResourceType::Rage).unwrap();
        assert_eq!(pool.max, 100.0);
        assert_eq!(pool.current, 0.0);
        assert!(pool.decays_out_of_combat);
    }

    #[test]
    fn resources_with_primary_combo_points() {
        let res = Resources::with_primary(ResourceType::ComboPoints);
        let pool = res.get(ResourceType::ComboPoints).unwrap();
        assert_eq!(pool.max, 5.0);
        assert_eq!(pool.regen_per_sec, 0.0);
    }

    #[test]
    fn resources_can_afford() {
        let mut res = Resources::with_primary(ResourceType::Energy);
        assert!(res.can_afford(ResourceType::Energy, 50.0));
        assert!(!res.can_afford(ResourceType::Energy, 150.0));
        assert!(!res.can_afford(ResourceType::Rage, 1.0));
        res.get_mut(ResourceType::Energy).unwrap().spend(80.0);
        assert!(!res.can_afford(ResourceType::Energy, 50.0));
    }

    #[test]
    fn resources_get_missing_returns_none() {
        let res = Resources::with_primary(ResourceType::Mana);
        assert!(res.get(ResourceType::Rage).is_none());
    }
}
